### ISSUE TITLE
Add custom html to an element 

### ISSUE THREAD

**Issue by tauseefk** [jillix/medium-editor-custom-html#3]
Hey I was wondering if there was a way to add an element after closing the current paragraph, or if I could define another container where I'd like the html element to be appended. 
I'm trying to achieve a layout where there are options next to each paragraph in the editor, which have some data related to the content of the paragraph.

**Comment by IonicaBizau** [comment]
@tauseefk I'm not sure what you're asking: currently, this library takes care of creating a new button with the text you're providing and inserting some HTML code at the position of cursor when clicking the button.

> add an element after closing the current paragraph, or if I could define another container where I'd like the html element to be appended. 

I'm not sure what you mean here.

**Comment by tauseefk** [comment]
What I mean is that currently say if I add an <hr> element it is added inside the element where my caret is, but I would like to add the <hr> element after closing the current element. Is there a way we can do that? 
I want to create accompanying text for example a comment, which should show up on the right side of my paragraph, currently if I add that element it comes inside the current element but I want it after the current element.

**Comment by IonicaBizau** [comment]
@tauseefk Actually, this should be possible by overwriting the `button.onclick` function:

```js
window.onload = function () {
    var customHtmlIns = new CustomHtml({
        buttonText: "<hr>"
      , htmlToInsert: "<hr class='someclass'>"
    });
    customHtmlIns.button.onclick = function () {
          /* do some stuff––insert after current paragraph something */
          alert("You clicked the button");
    };
    var myEditor = new MediumEditor(".container", {
        buttons: [
            "bold"
          , "italic"
          , "underline"
          , "anchor"
          , "header1"
          , "header2"
          , "quote"
          , "customHtml"
        ]
      , extensions: {
            "customHtml": customHtmlIns
        }
    });
};
```

Didn't test this code, but probably it should work. :sparkle:

**Comment by tauseefk** [comment]
Awesome thanks..!!

**Comment by IonicaBizau** [comment]
@tauseefk You're welcome! :joy:
